services:
  backend:
    build: ./backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: unless-stopped
    networks:
      - app-network
  frontend:
    build: ./frontend
    env_file:
      - .env
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - app-network
  ngrok:
    build: ./ngrok
    command: ["sh", "start.sh"]
    environment:
      - NGROK_AUTH_TOKEN=${NGROK_AUTH_TOKEN}
    depends_on:
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge