FROM alpine:latest

RUN apk add --no-cache wget unzip bash
WORKDIR /app

RUN wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-linux-amd64.zip && \
    unzip ngrok-stable-linux-amd64.zip && \
    mv ngrok /usr/local/bin && \
    rm ngrok-stable-linux-amd64.zip

COPY start.sh .
RUN chmod +x start.sh

CMD ["sh", "start.sh"]